# Generated by Django 5.1.6 on 2025-03-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('precio', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('fecha_vencimiento', models.DateField()),
            ],
        ),
    ]
